spring:
  application:
    name: zellpayment-api

server:
  port: 9090

logging:
  level:
    com:
      zellpayment: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/zellpayment.log
    path: ./logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
